theme = "elan"
title = "ELAN BARRY"
copyright = ""

#site parameters
[params]
description = "Elan's Website"

[[menu.main]]
name = "ABOUT"
url = "/about"

[[menu.main]]
name = "PORTFOLIO"
url = "/portfolio"

[params.contact]
description = "Find me on the web:"
linkedin = "https://www.linkedin.com/in/elan-barry-9a7163194/"
instagram = "https://www.instagram.com/elan.___/"
issuu = "https://issuu.com/elanbarry/docs/_"