theme = "elan"
title = "ELAN BARRY"
#site parameters
[params]
description = "Elan's Website"

[[menu.main]]
name = "ABOUT"
url = "/about"

[[menu.footer]]
name = "ABOUT"
url = "/about"

[[menu.footer]]
name = "PRIVACY"
url = "/privacy"

[params.contact]
linkedin = "#"
instagram = "#"
issuu = "#"