theme = "elan"
title = "Elan Barry"
#site parameters
[params]
description = "Elan's Website"

[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Blog"
url = "/blog"

[[menu.footer]]
name = "About"
url = "/about"

[[menu.footer]]
name = "Privacy"
url = "/privacy"